### ISSUE TITLE
NullPointerException when calendar.txt is empty

### ISSUE THREAD

**Issue by Platzii** [laidig/gtfs-validator#2]
Hi

I've noticed the validator crashes when the calendar.txt file is empty (just containing the headers).

Stacktrace:
```
Exception in thread "main" java.lang.NullPointerException
    at java.util.Calendar.setTime(Calendar.java:1770)
    at org.onebusaway.gtfs.model.calendar.ServiceDate.getCalendarForDate(ServiceDate.java:298)
    at org.onebusaway.gtfs.model.calendar.ServiceDate.<init>(ServiceDate.java:89)
    at com.conveyal.gtfs.service.CalendarDateVerificationService.<init>(CalendarDateVerificationService.java:55)
    at com.conveyal.gtfs.validator.ValidatorMain.main(ValidatorMain.java:70)
```

File used:
http://gtfs.irail.be/nmbs/nmbs-2016-12-1.zip

I don't know whether this is a valid GTFS format or not, but the validator shouldn't crash on this I suppose.
Could you check this out please?

Kind regards
Simon

**Comment by laidig** [comment]
I see that-- this is one of those rail feeds that has only calendar_dates. I will fix in the next few days. 

Thanks for the report and your interest!

**Comment by laidig** [comment]
Please check the new release.
